### ISSUE TITLE
bokeh html not rendering when using pelican on github pages

### ISSUE THREAD

**Issue by dtaylor072** [cfangmeier/markdown-bokeh#1]
Hi, I am having an issue when I attempt to use markdow-bokeh with pelican to render a static site (hosted on github pages). I have placed my plot .html and .js files in my `assets` folder and then called them in my post markdown with the syntax `{!basename!}(caption)`, but when I run `pelican content`, pelican treats the .html file as an `article`, rather than `static` (the .js file is treated as `static`). Thus, pelican refuses to copy the .html over from content to output and the plot is not rendered in the post. Does anyone have experience with integrating pelican and bokeh that can help me out with this?

**Comment by cfangmeier** [comment]
The html and js output from bokeh should not be placed in the directory that pelican looks into for your article content. This is because the way markdown-bokeh works is to literally insert the bokeh html and js into the final html of the article the plot is included in. (see [here](https://fangmeier.tech/grandpa-goes-to-washington.html) for an example of what this looks like.

What I find works well is to create a directory (or link to a directory) in my project root called (eg.) `bokeh_plots` which contains the html and js from running bokeh. Then, in my article in `assets` I refer to it like 

```
{!./bokeh_plots/my_plot!}(caption for my_plot)
```
I hope this helps.

**Comment by dtaylor072** [comment]
Thanks for the response! This does help. I have created a `bokeh_plots` directory in my pelican project root (and referenced the plots through that directory in my article), but the `bokeh_plots` directory is not copied over to output when running `pelican content`. Thus, the plots can't be referenced by the output html properly. Is there a way to solve this? Thanks again

**Comment by cfangmeier** [comment]
The `bokeh_plots` directory wouldn't be copied over. Instead, it's contents are inserted into the output html.

For example, if `bokeh_plots/` contains

`myplot.html`
```html
<div class="bk-root">
    <div class="bk-plotdiv" id="733e8373-b7fe-4884-ac84-3ca45e47d33e"></div>
</div>
```

`myplot.js`
```js
<script type="text/javascript">
  **snipped**
</script>
```

And my article is

`myarticle.md`
```md
Title: My Article

Here is a bokeh plot!

{!./bokeh_plots/myplot!}(My Caption)
```
Then the final html will contain something like:

```html
<h1>My Article</h1>
<p>Here is a bokeh plot!</p>
<figure>
<div class="bk-root">
    <div class="bk-plotdiv" id="733e8373-b7fe-4884-ac84-3ca45e47d33e"></div>
</div>
<figcaption>My Caption</figcaption>
</figure>
<script type="text/javascript">
  **snipped**
</script>
```
So the output html doesn't need to reference the original bokeh files since their content has been inserted into the output html.

**Comment by dtaylor072** [comment]
Okay, I understand now. I was able to get the proper .html and .js to copy over into the output html file (see: https://github.com/dtaylor072/dtaylor072.github.io/blob/master/post2.html), but the plot still does not render (see: https://dtaylor072.github.io/post2.html). I have the inserted the following into my `pelicanconf.py` :

```
MARKDOWN = {
    'extension_configs': {
        'markdown_bokeh.bokeh': {},
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
    },
    'output_format': 'html5',
}
```
Do you know what could be happening here? I really appreciate your help, this is huge for me as I get started with a pelican blog.

**Comment by cfangmeier** [comment]
Taking a quick peek at post2, it looks like you are missing the bokeh runtime js. Just edit your template to include 

```html
<script src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js"></script>
```
somewhere in the header and it should work.

I'm realizing now just how hacky/unintuitive this package is, but don't really have the time/motivation to improve it at the moment. :unamused: If you find the package useful and want to improve it though, I'm happy for any PRs.

**Comment by dtaylor072** [comment]
Got it! Thanks so much for your help on this
